export interface Stock {
  code: string;
  name: string;
  market: "KOSPI" | "KOSDAQ";
  isLargeCap: boolean;
}

export function getStockUniverse(): Stock[] {
  return [
    // KOSPI 대형주 (top 40 by market cap)
    { code: "005930", name: "삼성전자", market: "KOSPI", isLargeCap: true },
    { code: "000660", name: "SK하이닉스", market: "KOSPI", isLargeCap: true },
    { code: "207940", name: "삼성바이오로직스", market: "KOSPI", isLargeCap: true },
    { code: "373220", name: "LG에너지솔루션", market: "KOSPI", isLargeCap: true },
    { code: "005380", name: "현대차", market: "KOSPI", isLargeCap: true },
    { code: "000270", name: "기아", market: "KOSPI", isLargeCap: true },
    { code: "105560", name: "KB금융", market: "KOSPI", isLargeCap: true },
    { code: "068270", name: "셀트리온", market: "KOSPI", isLargeCap: true },
    { code: "005490", name: "POSCO홀딩스", market: "KOSPI", isLargeCap: true },
    { code: "006400", name: "삼성SDI", market: "KOSPI", isLargeCap: true },
    { code: "012330", name: "현대모비스", market: "KOSPI", isLargeCap: true },
    { code: "051910", name: "LG화학", market: "KOSPI", isLargeCap: true },
    { code: "028260", name: "삼성물산", market: "KOSPI", isLargeCap: true },
    { code: "035420", name: "NAVER", market: "KOSPI", isLargeCap: true },
    { code: "035720", name: "카카오", market: "KOSPI", isLargeCap: true },
    { code: "055550", name: "신한지주", market: "KOSPI", isLargeCap: true },
    { code: "086790", name: "하나금융지주", market: "KOSPI", isLargeCap: true },
    { code: "033780", name: "KT&G", market: "KOSPI", isLargeCap: true },
    { code: "066570", name: "LG전자", market: "KOSPI", isLargeCap: true },
    { code: "009150", name: "삼성전기", market: "KOSPI", isLargeCap: true },
    { code: "032830", name: "삼성생명", market: "KOSPI", isLargeCap: true },
    { code: "096770", name: "SK이노베이션", market: "KOSPI", isLargeCap: true },
    { code: "003550", name: "LG", market: "KOSPI", isLargeCap: true },
    { code: "034730", name: "SK", market: "KOSPI", isLargeCap: true },
    { code: "012450", name: "한화에어로스페이스", market: "KOSPI", isLargeCap: true },
    { code: "009540", name: "HD한국조선해양", market: "KOSPI", isLargeCap: true },
    { code: "267250", name: "HD현대", market: "KOSPI", isLargeCap: true },
    { code: "329180", name: "HD현대중공업", market: "KOSPI", isLargeCap: true },
    { code: "259960", name: "크래프톤", market: "KOSPI", isLargeCap: true },
    { code: "003670", name: "포스코퓨처엠", market: "KOSPI", isLargeCap: true },
    { code: "247540", name: "에코프로비엠", market: "KOSPI", isLargeCap: true },
    { code: "034020", name: "두산에너빌리티", market: "KOSPI", isLargeCap: true },
    { code: "015760", name: "한국전력", market: "KOSPI", isLargeCap: true },
    { code: "017670", name: "SK텔레콤", market: "KOSPI", isLargeCap: true },
    { code: "030200", name: "KT", market: "KOSPI", isLargeCap: true },
    { code: "011070", name: "LG이노텍", market: "KOSPI", isLargeCap: true },
    { code: "010130", name: "고려아연", market: "KOSPI", isLargeCap: true },
    { code: "003490", name: "대한항공", market: "KOSPI", isLargeCap: true },
    { code: "090430", name: "아모레퍼시픽", market: "KOSPI", isLargeCap: true },
    { code: "180640", name: "한진칼", market: "KOSPI", isLargeCap: true },

    // KOSPI 중소형주 (next 40)
    { code: "009830", name: "한화솔루션", market: "KOSPI", isLargeCap: false },
    { code: "161390", name: "한국타이어앤테크놀로지", market: "KOSPI", isLargeCap: false },
    { code: "000720", name: "현대건설", market: "KOSPI", isLargeCap: false },
    { code: "086280", name: "현대글로비스", market: "KOSPI", isLargeCap: false },
    { code: "023530", name: "롯데쇼핑", market: "KOSPI", isLargeCap: false },
    { code: "004170", name: "신세계", market: "KOSPI", isLargeCap: false },
    { code: "006360", name: "GS건설", market: "KOSPI", isLargeCap: false },
    { code: "000880", name: "한화", market: "KOSPI", isLargeCap: false },
    { code: "139480", name: "이마트", market: "KOSPI", isLargeCap: false },
    { code: "002380", name: "KCC", market: "KOSPI", isLargeCap: false },
    { code: "011780", name: "금호석유", market: "KOSPI", isLargeCap: false },
    { code: "010060", name: "OCI홀딩스", market: "KOSPI", isLargeCap: false },
    { code: "011200", name: "HMM", market: "KOSPI", isLargeCap: false },
    { code: "042660", name: "한화오션", market: "KOSPI", isLargeCap: false },
    { code: "004020", name: "현대제철", market: "KOSPI", isLargeCap: false },
    { code: "002350", name: "넥센타이어", market: "KOSPI", isLargeCap: false },
    { code: "010140", name: "삼성중공업", market: "KOSPI", isLargeCap: false },
    { code: "298040", name: "효성중공업", market: "KOSPI", isLargeCap: false },
    { code: "071050", name: "한국금융지주", market: "KOSPI", isLargeCap: false },
    { code: "030000", name: "제일기획", market: "KOSPI", isLargeCap: false },
    { code: "078930", name: "GS", market: "KOSPI", isLargeCap: false },
    { code: "375500", name: "DL이앤씨", market: "KOSPI", isLargeCap: false },
    { code: "000100", name: "유한양행", market: "KOSPI", isLargeCap: false },
    { code: "128940", name: "한미약품", market: "KOSPI", isLargeCap: false },
    { code: "185750", name: "종근당", market: "KOSPI", isLargeCap: false },
    { code: "069620", name: "대웅제약", market: "KOSPI", isLargeCap: false },
    { code: "003850", name: "보령", market: "KOSPI", isLargeCap: false },
    { code: "007570", name: "일양약품", market: "KOSPI", isLargeCap: false },
    { code: "015750", name: "성우하이텍", market: "KOSPI", isLargeCap: false },
    { code: "000990", name: "DB하이텍", market: "KOSPI", isLargeCap: false },
    { code: "011170", name: "롯데케미칼", market: "KOSPI", isLargeCap: false },
    { code: "097950", name: "CJ제일제당", market: "KOSPI", isLargeCap: false },
    { code: "079550", name: "LIG넥스원", market: "KOSPI", isLargeCap: false },
    { code: "071970", name: "HD현대마린엔진", market: "KOSPI", isLargeCap: false },
    { code: "352820", name: "하이브", market: "KOSPI", isLargeCap: false },
    { code: "036570", name: "엔씨소프트", market: "KOSPI", isLargeCap: false },
    { code: "018880", name: "한온시스템", market: "KOSPI", isLargeCap: false },
    { code: "005070", name: "코스모신소재", market: "KOSPI", isLargeCap: false },
    { code: "018670", name: "SK가스", market: "KOSPI", isLargeCap: false },
    { code: "032640", name: "LG유플러스", market: "KOSPI", isLargeCap: false },

    // KOSDAQ 대형주 (top 40 by market cap)
    { code: "086520", name: "에코프로", market: "KOSDAQ", isLargeCap: true },
    { code: "196170", name: "알테오젠", market: "KOSDAQ", isLargeCap: true },
    { code: "141080", name: "리가켐바이오", market: "KOSDAQ", isLargeCap: true },
    { code: "028300", name: "HLB", market: "KOSDAQ", isLargeCap: true },
    { code: "214150", name: "클래시스", market: "KOSDAQ", isLargeCap: true },
    { code: "278470", name: "에이피알", market: "KOSDAQ", isLargeCap: true },
    { code: "068240", name: "다원시스", market: "KOSDAQ", isLargeCap: true },
    { code: "293490", name: "카카오게임즈", market: "KOSDAQ", isLargeCap: true },
    { code: "263750", name: "펄어비스", market: "KOSDAQ", isLargeCap: true },
    { code: "357780", name: "솔브레인", market: "KOSDAQ", isLargeCap: true },
    { code: "035760", name: "CJ ENM", market: "KOSDAQ", isLargeCap: true },
    { code: "253450", name: "스튜디오드래곤", market: "KOSDAQ", isLargeCap: true },
    { code: "145020", name: "휴젤", market: "KOSDAQ", isLargeCap: true },
    { code: "086900", name: "메디톡스", market: "KOSDAQ", isLargeCap: true },
    { code: "214520", name: "에이비엘바이오", market: "KOSDAQ", isLargeCap: true },
    { code: "121600", name: "나노신소재", market: "KOSDAQ", isLargeCap: true },
    { code: "277810", name: "레인보우로보틱스", market: "KOSDAQ", isLargeCap: true },
    { code: "215200", name: "메가스터디교육", market: "KOSDAQ", isLargeCap: true },
    { code: "319660", name: "피에스케이", market: "KOSDAQ", isLargeCap: true },
    { code: "383310", name: "에코프로에이치엔", market: "KOSDAQ", isLargeCap: true },
    { code: "112040", name: "위메이드", market: "KOSDAQ", isLargeCap: true },
    { code: "041510", name: "에스엠", market: "KOSDAQ", isLargeCap: true },
    { code: "035900", name: "JYP Ent.", market: "KOSDAQ", isLargeCap: true },
    { code: "122870", name: "와이지엔터테인먼트", market: "KOSDAQ", isLargeCap: true },
    { code: "086050", name: "모비스", market: "KOSDAQ", isLargeCap: true },
    { code: "058470", name: "리노공업", market: "KOSDAQ", isLargeCap: true },
    { code: "237690", name: "에스티팜", market: "KOSDAQ", isLargeCap: true },
    { code: "950130", name: "엑세스바이오", market: "KOSDAQ", isLargeCap: true },
    { code: "215600", name: "신라젠", market: "KOSDAQ", isLargeCap: true },
    { code: "067160", name: "아프리카TV", market: "KOSDAQ", isLargeCap: true },
    { code: "079160", name: "CJ CGV", market: "KOSDAQ", isLargeCap: true },
    { code: "348950", name: "뷰웍스", market: "KOSDAQ", isLargeCap: true },
    { code: "376300", name: "디어유", market: "KOSDAQ", isLargeCap: true },
    { code: "101490", name: "에스앤에스텍", market: "KOSDAQ", isLargeCap: true },
    { code: "073240", name: "금호타이어", market: "KOSDAQ", isLargeCap: true },
    { code: "166090", name: "하나머티리얼즈", market: "KOSDAQ", isLargeCap: true },
    { code: "206560", name: "덱스터", market: "KOSDAQ", isLargeCap: true },
    { code: "031820", name: "케이아이엔엑스", market: "KOSDAQ", isLargeCap: true },
    { code: "078520", name: "에이블씨엔씨", market: "KOSDAQ", isLargeCap: true },
    { code: "039030", name: "이오테크닉스", market: "KOSDAQ", isLargeCap: true },

    // KOSDAQ 중소형주 (next 40)
    { code: "214450", name: "파마리서치", market: "KOSDAQ", isLargeCap: false },
    { code: "086450", name: "동국제약", market: "KOSDAQ", isLargeCap: false },
    { code: "250250", name: "하이로닉", market: "KOSDAQ", isLargeCap: false },
    { code: "307950", name: "현대오토에버", market: "KOSDAQ", isLargeCap: false },
    { code: "137310", name: "에스디바이오센서", market: "KOSDAQ", isLargeCap: false },
    { code: "144510", name: "지씨셀", market: "KOSDAQ", isLargeCap: false },
    { code: "170900", name: "동아에스티", market: "KOSDAQ", isLargeCap: false },
    { code: "115180", name: "큐리언트", market: "KOSDAQ", isLargeCap: false },
    { code: "036540", name: "SFA반도체", market: "KOSDAQ", isLargeCap: false },
    { code: "095660", name: "네오위즈", market: "KOSDAQ", isLargeCap: false },
    { code: "060310", name: "3S", market: "KOSDAQ", isLargeCap: false },
    { code: "109610", name: "에스와이", market: "KOSDAQ", isLargeCap: false },
    { code: "089980", name: "알티오라", market: "KOSDAQ", isLargeCap: false },
    { code: "246690", name: "에스앤더블류", market: "KOSDAQ", isLargeCap: false },
    { code: "102120", name: "어보브반도체", market: "KOSDAQ", isLargeCap: false },
    { code: "222040", name: "코리아나", market: "KOSDAQ", isLargeCap: false },
    { code: "200230", name: "플레이디", market: "KOSDAQ", isLargeCap: false },
    { code: "330860", name: "스튜디오미르", market: "KOSDAQ", isLargeCap: false },
    { code: "049550", name: "인탑스", market: "KOSDAQ", isLargeCap: false },
    { code: "066790", name: "씨씨에스", market: "KOSDAQ", isLargeCap: false },
    { code: "039440", name: "에스티아이", market: "KOSDAQ", isLargeCap: false },
    { code: "091120", name: "이엠텍", market: "KOSDAQ", isLargeCap: false },
    { code: "083470", name: "이크레더블", market: "KOSDAQ", isLargeCap: false },
    { code: "290550", name: "디앤씨미디어", market: "KOSDAQ", isLargeCap: false },
    { code: "196300", name: "애니플러스", market: "KOSDAQ", isLargeCap: false },
    { code: "052670", name: "디씨엠", market: "KOSDAQ", isLargeCap: false },
    { code: "036360", name: "씨엔에스", market: "KOSDAQ", isLargeCap: false },
    { code: "256940", name: "케이피에스", market: "KOSDAQ", isLargeCap: false },
    { code: "119650", name: "코스나인", market: "KOSDAQ", isLargeCap: false },
    { code: "084370", name: "유진테크", market: "KOSDAQ", isLargeCap: false },
    { code: "024060", name: "흥구석유", market: "KOSDAQ", isLargeCap: false },
    { code: "058450", name: "엔에스쇼핑", market: "KOSDAQ", isLargeCap: false },
    { code: "268280", name: "에이치피오", market: "KOSDAQ", isLargeCap: false },
    { code: "064800", name: "젠큐릭스", market: "KOSDAQ", isLargeCap: false },
    { code: "138230", name: "지엔코", market: "KOSDAQ", isLargeCap: false },
    { code: "065350", name: "신성델타테크", market: "KOSDAQ", isLargeCap: false },
    { code: "051510", name: "알에프텍", market: "KOSDAQ", isLargeCap: false },
    { code: "064090", name: "웨이버스", market: "KOSDAQ", isLargeCap: false },
    { code: "078130", name: "마이크로컨텍솔", market: "KOSDAQ", isLargeCap: false },
    { code: "069410", name: "엔텔스", market: "KOSDAQ", isLargeCap: false },
  ];
}
